/**
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 *
 * OpenAPI spec version: 0.7.5
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */



/**
 * 200 ok object
 */
export interface GetCorporationsCorporationIdContainersLogs200Ok {
    /**
     * Timestamp when this log was created
     */
    loggedAt: Date;

    /**
     * ID of the container
     */
    containerId: number;

    /**
     * Type ID of the container
     */
    containerTypeId: number;

    /**
     * ID of the character who performed the action.
     */
    characterId: number;

    /**
     * location_id integer
     */
    locationId: number;

    /**
     * location_flag string
     */
    locationFlag: GetCorporationsCorporationIdContainersLogs200Ok.LocationFlagEnum;

    /**
     * action string
     */
    action: GetCorporationsCorporationIdContainersLogs200Ok.ActionEnum;

    /**
     * Type of password set if action is of type SetPassword or EnterPassword
     */
    passwordType?: GetCorporationsCorporationIdContainersLogs200Ok.PasswordTypeEnum;

    /**
     * Type ID of the item being acted upon
     */
    typeId?: number;

    /**
     * Quantity of the item being acted upon
     */
    quantity?: number;

    /**
     * old_config_bitmask integer
     */
    oldConfigBitmask?: number;

    /**
     * new_config_bitmask integer
     */
    newConfigBitmask?: number;

}
export namespace GetCorporationsCorporationIdContainersLogs200Ok {
    export enum LocationFlagEnum {
        AssetSafety = <any> 'AssetSafety',
        AutoFit = <any> 'AutoFit',
        Bonus = <any> 'Bonus',
        Booster = <any> 'Booster',
        BoosterBay = <any> 'BoosterBay',
        Capsule = <any> 'Capsule',
        Cargo = <any> 'Cargo',
        CorpDeliveries = <any> 'CorpDeliveries',
        CorpSAG1 = <any> 'CorpSAG1',
        CorpSAG2 = <any> 'CorpSAG2',
        CorpSAG3 = <any> 'CorpSAG3',
        CorpSAG4 = <any> 'CorpSAG4',
        CorpSAG5 = <any> 'CorpSAG5',
        CorpSAG6 = <any> 'CorpSAG6',
        CorpSAG7 = <any> 'CorpSAG7',
        CrateLoot = <any> 'CrateLoot',
        Deliveries = <any> 'Deliveries',
        DroneBay = <any> 'DroneBay',
        DustBattle = <any> 'DustBattle',
        DustDatabank = <any> 'DustDatabank',
        FighterBay = <any> 'FighterBay',
        FighterTube0 = <any> 'FighterTube0',
        FighterTube1 = <any> 'FighterTube1',
        FighterTube2 = <any> 'FighterTube2',
        FighterTube3 = <any> 'FighterTube3',
        FighterTube4 = <any> 'FighterTube4',
        FleetHangar = <any> 'FleetHangar',
        Hangar = <any> 'Hangar',
        HangarAll = <any> 'HangarAll',
        HiSlot0 = <any> 'HiSlot0',
        HiSlot1 = <any> 'HiSlot1',
        HiSlot2 = <any> 'HiSlot2',
        HiSlot3 = <any> 'HiSlot3',
        HiSlot4 = <any> 'HiSlot4',
        HiSlot5 = <any> 'HiSlot5',
        HiSlot6 = <any> 'HiSlot6',
        HiSlot7 = <any> 'HiSlot7',
        HiddenModifers = <any> 'HiddenModifers',
        Implant = <any> 'Implant',
        Impounded = <any> 'Impounded',
        JunkyardReprocessed = <any> 'JunkyardReprocessed',
        JunkyardTrashed = <any> 'JunkyardTrashed',
        LoSlot0 = <any> 'LoSlot0',
        LoSlot1 = <any> 'LoSlot1',
        LoSlot2 = <any> 'LoSlot2',
        LoSlot3 = <any> 'LoSlot3',
        LoSlot4 = <any> 'LoSlot4',
        LoSlot5 = <any> 'LoSlot5',
        LoSlot6 = <any> 'LoSlot6',
        LoSlot7 = <any> 'LoSlot7',
        Locked = <any> 'Locked',
        MedSlot0 = <any> 'MedSlot0',
        MedSlot1 = <any> 'MedSlot1',
        MedSlot2 = <any> 'MedSlot2',
        MedSlot3 = <any> 'MedSlot3',
        MedSlot4 = <any> 'MedSlot4',
        MedSlot5 = <any> 'MedSlot5',
        MedSlot6 = <any> 'MedSlot6',
        MedSlot7 = <any> 'MedSlot7',
        OfficeFolder = <any> 'OfficeFolder',
        Pilot = <any> 'Pilot',
        PlanetSurface = <any> 'PlanetSurface',
        QuafeBay = <any> 'QuafeBay',
        Reward = <any> 'Reward',
        RigSlot0 = <any> 'RigSlot0',
        RigSlot1 = <any> 'RigSlot1',
        RigSlot2 = <any> 'RigSlot2',
        RigSlot3 = <any> 'RigSlot3',
        RigSlot4 = <any> 'RigSlot4',
        RigSlot5 = <any> 'RigSlot5',
        RigSlot6 = <any> 'RigSlot6',
        RigSlot7 = <any> 'RigSlot7',
        SecondaryStorage = <any> 'SecondaryStorage',
        ServiceSlot0 = <any> 'ServiceSlot0',
        ServiceSlot1 = <any> 'ServiceSlot1',
        ServiceSlot2 = <any> 'ServiceSlot2',
        ServiceSlot3 = <any> 'ServiceSlot3',
        ServiceSlot4 = <any> 'ServiceSlot4',
        ServiceSlot5 = <any> 'ServiceSlot5',
        ServiceSlot6 = <any> 'ServiceSlot6',
        ServiceSlot7 = <any> 'ServiceSlot7',
        ShipHangar = <any> 'ShipHangar',
        ShipOffline = <any> 'ShipOffline',
        Skill = <any> 'Skill',
        SkillInTraining = <any> 'SkillInTraining',
        SpecializedAmmoHold = <any> 'SpecializedAmmoHold',
        SpecializedCommandCenterHold = <any> 'SpecializedCommandCenterHold',
        SpecializedFuelBay = <any> 'SpecializedFuelBay',
        SpecializedGasHold = <any> 'SpecializedGasHold',
        SpecializedIndustrialShipHold = <any> 'SpecializedIndustrialShipHold',
        SpecializedLargeShipHold = <any> 'SpecializedLargeShipHold',
        SpecializedMaterialBay = <any> 'SpecializedMaterialBay',
        SpecializedMediumShipHold = <any> 'SpecializedMediumShipHold',
        SpecializedMineralHold = <any> 'SpecializedMineralHold',
        SpecializedOreHold = <any> 'SpecializedOreHold',
        SpecializedPlanetaryCommoditiesHold = <any> 'SpecializedPlanetaryCommoditiesHold',
        SpecializedSalvageHold = <any> 'SpecializedSalvageHold',
        SpecializedShipHold = <any> 'SpecializedShipHold',
        SpecializedSmallShipHold = <any> 'SpecializedSmallShipHold',
        StructureActive = <any> 'StructureActive',
        StructureFuel = <any> 'StructureFuel',
        StructureInactive = <any> 'StructureInactive',
        StructureOffline = <any> 'StructureOffline',
        SubSystemSlot0 = <any> 'SubSystemSlot0',
        SubSystemSlot1 = <any> 'SubSystemSlot1',
        SubSystemSlot2 = <any> 'SubSystemSlot2',
        SubSystemSlot3 = <any> 'SubSystemSlot3',
        SubSystemSlot4 = <any> 'SubSystemSlot4',
        SubSystemSlot5 = <any> 'SubSystemSlot5',
        SubSystemSlot6 = <any> 'SubSystemSlot6',
        SubSystemSlot7 = <any> 'SubSystemSlot7',
        SubsystemBay = <any> 'SubsystemBay',
        Unlocked = <any> 'Unlocked',
        Wallet = <any> 'Wallet',
        Wardrobe = <any> 'Wardrobe'
    }
    export enum ActionEnum {
        Add = <any> 'add',
        Assemble = <any> 'assemble',
        Configure = <any> 'configure',
        EnterPassword = <any> 'enter_password',
        Lock = <any> 'lock',
        Move = <any> 'move',
        Repackage = <any> 'repackage',
        SetName = <any> 'set_name',
        SetPassword = <any> 'set_password',
        Unlock = <any> 'unlock'
    }
    export enum PasswordTypeEnum {
        Config = <any> 'config',
        General = <any> 'general'
    }
}
