/**
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 *
 * OpenAPI spec version: 0.7.5
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */



/**
 * event
 */
export interface GetCharactersCharacterIdCalendar200Ok {
    /**
     * event_id integer
     */
    eventId?: number;

    /**
     * event_date string
     */
    eventDate?: Date;

    /**
     * title string
     */
    title?: string;

    /**
     * importance integer
     */
    importance?: number;

    /**
     * event_response string
     */
    eventResponse?: GetCharactersCharacterIdCalendar200Ok.EventResponseEnum;

}
export namespace GetCharactersCharacterIdCalendar200Ok {
    export enum EventResponseEnum {
        Declined = <any> 'declined',
        NotResponded = <any> 'not_responded',
        Accepted = <any> 'accepted',
        Tentative = <any> 'tentative'
    }
}
