/**
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 *
 * OpenAPI spec version: 0.7.5
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */



/**
 * 200 ok object
 */
export interface GetCorporationsCorporationIdContacts200Ok {
    /**
     * Standing of the contact
     */
    standing: number;

    /**
     * contact_type string
     */
    contactType: GetCorporationsCorporationIdContacts200Ok.ContactTypeEnum;

    /**
     * contact_id integer
     */
    contactId: number;

    /**
     * Whether this contact is being watched
     */
    isWatched?: boolean;

    /**
     * Custom label of the contact
     */
    labelId?: number;

}
export namespace GetCorporationsCorporationIdContacts200Ok {
    export enum ContactTypeEnum {
        Character = <any> 'character',
        Corporation = <any> 'corporation',
        Alliance = <any> 'alliance',
        Faction = <any> 'faction'
    }
}
