/**
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 *
 * OpenAPI spec version: 0.7.5
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */



/**
 * 200 ok object
 */
export interface GetUniverseStarsStarIdOk {
    /**
     * name string
     */
    name: string;

    /**
     * solar_system_id integer
     */
    solarSystemId: number;

    /**
     * type_id integer
     */
    typeId: number;

    /**
     * Age of star in years
     */
    age: number;

    /**
     * luminosity number
     */
    luminosity: number;

    /**
     * radius integer
     */
    radius: number;

    /**
     * spectral_class string
     */
    spectralClass: GetUniverseStarsStarIdOk.SpectralClassEnum;

    /**
     * temperature integer
     */
    temperature: number;

}
export namespace GetUniverseStarsStarIdOk {
    export enum SpectralClassEnum {
        K2V = <any> 'K2 V',
        K4V = <any> 'K4 V',
        G2V = <any> 'G2 V',
        G8V = <any> 'G8 V',
        M7V = <any> 'M7 V',
        K7V = <any> 'K7 V',
        M2V = <any> 'M2 V',
        K5V = <any> 'K5 V',
        M3V = <any> 'M3 V',
        G0V = <any> 'G0 V',
        G7V = <any> 'G7 V',
        G3V = <any> 'G3 V',
        F9V = <any> 'F9 V',
        G5V = <any> 'G5 V',
        F6V = <any> 'F6 V',
        K8V = <any> 'K8 V',
        K9V = <any> 'K9 V',
        K6V = <any> 'K6 V',
        G9V = <any> 'G9 V',
        G6V = <any> 'G6 V',
        G4VI = <any> 'G4 VI',
        G4V = <any> 'G4 V',
        F8V = <any> 'F8 V',
        F2V = <any> 'F2 V',
        F1V = <any> 'F1 V',
        K3V = <any> 'K3 V',
        F0VI = <any> 'F0 VI',
        G1VI = <any> 'G1 VI',
        G0VI = <any> 'G0 VI',
        K1V = <any> 'K1 V',
        M4V = <any> 'M4 V',
        M1V = <any> 'M1 V',
        M6V = <any> 'M6 V',
        M0V = <any> 'M0 V',
        K2IV = <any> 'K2 IV',
        G2VI = <any> 'G2 VI',
        K0V = <any> 'K0 V',
        K5IV = <any> 'K5 IV',
        F5VI = <any> 'F5 VI',
        G6VI = <any> 'G6 VI',
        F6VI = <any> 'F6 VI',
        F2IV = <any> 'F2 IV',
        G3VI = <any> 'G3 VI',
        M8V = <any> 'M8 V',
        F1VI = <any> 'F1 VI',
        K1IV = <any> 'K1 IV',
        F7V = <any> 'F7 V',
        G5VI = <any> 'G5 VI',
        M5V = <any> 'M5 V',
        G7VI = <any> 'G7 VI',
        F5V = <any> 'F5 V',
        F4VI = <any> 'F4 VI',
        F8VI = <any> 'F8 VI',
        K3IV = <any> 'K3 IV',
        F4IV = <any> 'F4 IV',
        F0V = <any> 'F0 V',
        G7IV = <any> 'G7 IV',
        G8VI = <any> 'G8 VI',
        F2VI = <any> 'F2 VI',
        F4V = <any> 'F4 V',
        F7VI = <any> 'F7 VI',
        F3V = <any> 'F3 V',
        G1V = <any> 'G1 V',
        G9VI = <any> 'G9 VI',
        F3IV = <any> 'F3 IV',
        F9VI = <any> 'F9 VI',
        M9V = <any> 'M9 V',
        K0IV = <any> 'K0 IV',
        F1IV = <any> 'F1 IV',
        G4IV = <any> 'G4 IV',
        F3VI = <any> 'F3 VI',
        K4IV = <any> 'K4 IV',
        G5IV = <any> 'G5 IV',
        G3IV = <any> 'G3 IV',
        G1IV = <any> 'G1 IV',
        K7IV = <any> 'K7 IV',
        G0IV = <any> 'G0 IV',
        K6IV = <any> 'K6 IV',
        K9IV = <any> 'K9 IV',
        G2IV = <any> 'G2 IV',
        F9IV = <any> 'F9 IV',
        F0IV = <any> 'F0 IV',
        K8IV = <any> 'K8 IV',
        G8IV = <any> 'G8 IV',
        F6IV = <any> 'F6 IV',
        F5IV = <any> 'F5 IV',
        A0 = <any> 'A0',
        A0IV = <any> 'A0IV',
        A0IV2 = <any> 'A0IV2'
    }
}
